### ISSUE TITLE
-Access the Dashboard- Forward emails to gmail, yahoo etc

### ISSUE THREAD

**Issue by FeelsBadMan1** [ScRiPt1337/spam_box#1]
Hello, i own a Linux Debian 10 vServer and i did ran the script. i needed to change the ip and port so as the ip i used the localhost (127.0.0.1) and as the port i used 1 number higher than the standard port. It seemed like it executed correctly but i dont know, how im supposed to visit the dashboard because i only have a terminal and not a gui on this vServer.

Edit:
I managed to install a gui on a new ubuntu vServer however it now shows any_name@0.0.0.0 as the mail and this is defently not a valid domain. is there a way to set a own custom domain?

**Comment by FeelsBadMan1** [comment]
> > > Don't change the port or IP and access the GUI using your custom domain so it will show [any_name@your_own_domain.com](mailto:any_name@your_own_domain.com)
> > 
> > 
> > Well i think i solved it. i now can send emials and they also will be shown however i only can see the id, the subject and a delte button. i cant see the message content is it possible to see the content? clicking on the entiy not did a thing
> 
> please send me a screenshot with a video if you can

Im not at home at the moment but i will send it when im at home.

**Comment by ScRiPt1337** [comment]
> This is a screenshot how it looks. I cant click on the mail and if needed i do a video at home: ![image](https://user-images.githubusercontent.com/40109798/138114055-cd02011a-132f-438e-8c4c-5b70494a19ff.png)



> This is a screenshot how it looks. I cant click on the mail and if needed i do a video at home: ![image](https://user-images.githubusercontent.com/40109798/138114055-cd02011a-132f-438e-8c4c-5b70494a19ff.png)

its fixed now
